name: Run at 8:15 AM CST on March 28

on:
  schedule:
    - cron: '15 13 28 3 *'
  workflow_dispatch:

jobs:
  run-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello
        run: echo "hello"
