name: BQ Test
on:
  push:
    branches:
      - main

jobs:
  print_secret:
    runs-on: windows-latest
    steps: 
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Print working directory
        run: Get-Location
        shell: pwsh

      - name: Set GCS auth and configure .Renviron
        run: |
          $jsonPath = "${{ runner.temp }}\gcs-auth.json"
          $renvironPath = "${{ github.workspace }}\.Renviron"
          Set-Content -Path $jsonPath -Value '${{ secrets.GCS_AUTH_FILE }}'
          Add-Content -Path $renvironPath -Value "GCS_AUTH_FILE=$jsonPath"
        shell: pwsh

      - name: Show .Renviron content
        run: Get-Content "${{ github.workspace }}\.Renviron"
        shell: pwsh

      - name: Set R_ENVIRON_USER for R
        run: echo "R_ENVIRON_USER=${{ github.workspace }}\\.Renviron" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # - name: Check GCS_AUTH_FILE in R
      #   run: |
      #     Rscript -e 'cat("GCS_AUTH_FILE:\n")'
      #     Rscript -e 'cat(Sys.getenv("GCS_AUTH_FILE"), "\n")'
      #   shell: pwsh

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_cran(c("shiny", "bslib", "plotly", "dplyr", "htmltools"), dependencies = TRUE)'
          Rscript -e 'remotes::install_cran(c("shinyWidgets", "DT", "tippy", "shinycssloaders"), dependencies = TRUE)'
          Rscript -e 'remotes::install_cran(c("glue", "leaflet", "testthat"), dependencies = TRUE)'
          Rscript -e 'remotes::install_cran("bigrquery", dependencies = TRUE)'
        shell: pwsh

      - name: Run R script
        run: Rscript tests/testthat_judy.R
        shell: pwsh



      
