name: Run on March 28 at 8:06 AM CST

on:
  schedule:
    - cron: '6 13 28 3 *'  # 8:06 AM CST = 13:06 UTC on March 28

jobs:
  run-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello
        run: echo "hello"
