# name: Deploy Shiny App to shinyapps.io (Optimized)

# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     env:
#       R_LIBS_USER: ${{ runner.temp }}/Rlibs
#       CRAN_REPO: https://packagemanager.posit.co/cran/latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Set up R
#         uses: r-lib/actions/setup-r@v2

#       - name: Install system dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y \
#             libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev \
#             libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev \
#             libtiff5-dev libjpeg-dev libgdal-dev libgeos-dev libproj-dev \
#             libv8-dev pandoc

#       - name: Set CRAN repo to RSPM
#         run: echo "options(repos = c(CRAN = '${{ env.CRAN_REPO }}'))" >> ~/.Rprofile

#       - name: Cache R packages
#         uses: actions/cache@v4
#         with:
#           path: ${{ env.R_LIBS_USER }}
#           key: r-${{ runner.os }}-${{ hashFiles('DESCRIPTION') }}
#           restore-keys: r-${{ runner.os }}-

#       - name: Install R packages
#         run: |
#           dir.create(Sys.getenv("R_LIBS_USER"), showWarnings = FALSE, recursive = TRUE)
#           .libPaths(Sys.getenv("R_LIBS_USER"))
#           install.packages(c(
#             "shiny", "bslib", "plotly", "leaflet", "DT",
#             "lubridate", "tippy", "sf", "rmapshaper", "glue", "htmltools",
#             "dplyr", "readr", "bigrquery", "googleAuthR", "rsconnect"
#           ))
#         shell: Rscript {0}

