name: macOS R Shiny Setup with BigQuery

on:
  workflow_dispatch:

jobs:
  setup-macos-r-env:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies via Homebrew
        run: |
          brew install pkg-config gdal geos proj cairo

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c(
            "shiny", "bslib", "plotly", "leaflet", "DT",
            "lubridate", "tippy", "sf", "rmapshaper", "glue",
            "htmltools", "dplyr", "readr", "bigrquery", "DBI", "googleAuthR"
          ))'
