name: Teams Message Test

on:
  workflow_dispatch:

jobs:
  send-teams-message:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Time
        id: time
        run: echo "now=$(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_OUTPUT

      - name: Send message to Teams
        run: |
          msg="🕒 Time: ${{ steps.time.outputs.now }}\n👋 Hey I am from GitHub Actions 😎"
          payload="{\"text\": \"$msg\"}"
          curl -H "Content-Type: application/json" \
               -d "$payload" \
               ${{ secrets.TEAMS_WEBHOOK_URL }}
