name: Send Power Automate Trigger

on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Power Automate flow
        run: |
          now=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          payload="{\"message\": \"Hey from GitHub Actions 🤖 at $now\"}"

          curl -X POST "${{ secrets.TEAMS_WEBHOOK_URL }}" \
               -H "Content-Type: application/json" \
               -d "$payload"
